### ISSUE TITLE
First docs

### ISSUE THREAD

**Issue by mstrk** [Cloudoki/appdoki-rn#4]
Write a basic documentation in order to setup and run the project in develop mode.

**Comment by jonwk** [comment]
Hey @mstrk, I'd like to work on this, can you please tell me how can I get started

**Comment by mstrk** [comment]
Hi @JohnWesleyK, I'm not sure how you can help. This app is for our hackfridays projects where we test new tech and show technical clients some portfolio and architecture.

This is also a slow paced project as we don’t have hackfridays every week, so it would be very boring for others to contribute.

But I'm probably going to write some docs on how to transfer this project to your own organisation in the future, if time allows.

Thank you for your interest nevertheless!

**Comment by jonwk** [comment]
No worries @mstrk thanks for the reply
